<?php
/**
 * Created by PhpStorm.
 * User: alice
 * Date: 2017/11/30
 * Time: 下午4:12
 */

namespace backend\controllers;


use common\base\NoCsrf;
use yii\web\Controller;

class WeChatController extends Controller
{
    private $postXml;   //接收微信传入的xml

    private $postObj;   //接收xml转换成的对象

    private $myId;  //微信公众号ID    gh_24696e54a9b1

    private $openId; //访问人openID    og8XAwhR970_A1BkxAt7uB-3LT8Y

    private $createTime;  //请求建立时间

    private $msgType;   //消息类型

    private $event; //时间类型

    private $eventKey;

    private $encrypt;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => NoCsrf::className(),
                'controller' => $this,
                'actions' => [
                    'index',
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        //获得参数 signature nonce token timestamp echostr
        $nonce     = $_GET['nonce'];
        $token     = 'alice';
        $timestamp = $_GET['timestamp'];
        $signature = $_GET['signature'];
        //形成数组，然后按字典序排序
        $array = array($nonce, $timestamp, $token);
        sort($array);
        //拼接成字符串,sha1加密 ，然后与signature进行校验
        $str = sha1( implode( $array ) );
        if( $str  == $signature && isset($_GET['echostr']) ){
            //第一次接入weixin api接口的时候
            echo  $_GET['echostr'];
            exit;
        }else{
            /*<xml>
                <ToUserName><![CDATA[gh_24696e54a9b1]]></ToUserName>
                <FromUserName><![CDATA[og8XAwhR970_A1BkxAt7uB-3LT8Y]]></FromUserName>
                <CreateTime>1512204708</CreateTime>
                <MsgType><![CDATA[event]]></MsgType>
                <Event><![CDATA[subscribe]]></Event>
                <EventKey><![CDATA[]]></EventKey>
                <Encrypt><![CDATA[UoMUMP3WKooFFFz6iWF85R/8QL7wXyQb3HWclamiMOJb2gIZHWrqQS8E4hd//eqhqh9m+rSE72w5UlR3uYsHI5M9aXqNT0NyoEEgb1krnqYih1EP05HlfyQjMOcQ7YUB3icYZ91CmwiKNl8KmMWuQhP8xu3MSxK+8tN9jU0mfL0GrVCisky936Qaerw8dh60AcfMXZEEqmX4q3J7dNVj5c3Lnj7YoERvKEZ6NxQq/iUrODwWkbdFT7iraRioU7VNzPPS/dUF1c0t7CfeENmcDdjHGcqROre/mJzQXvv9YzeAHI1y7C/Bg63YLBunSo5mZSSwsqEQpHz1KPY05FrjIDjlDA+tJbDxmafIXf4NqoT4S48+IjLNSa1VZjWWzu2uGcmOnzo3x5Zxm3j/zHgaZRg7CuP8F3/rXsGTC3xSBdE=]]></Encrypt>
            </xml>*/
            //1.获取到微信推送过来post数据
            $this->postXml = file_get_contents("php://input");
            //2.处理消息类型，并设置回复类型和内容
            $this->postObj = simplexml_load_string($this->postXml);

            $this->myId = $this->postObj->ToUserName;
            $this->openId = $this->postObj->FromUserName;
            $this->createTime = $this->postObj->CreateTime;
            $this->msgType = strtolower($this->postObj->MsgType);
            $this->event = strtolower($this->postObj->Event);
            $this->eventKey = $this->postObj->EventKey;
            $this->encrypt = $this->postObj->Encrypt;

            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        }
    }

    public function actionIndex(){
        if ($this->msgType == 'event' && $this->event == 'subscribe') {
            //详细为事件类型，并且是关注事件
            $this->subscribe();
        }
    }

    //关注事件回复
    public function subscribe()
    {
        $msgType = 'text';
        $content = '欢迎关注';
        $this->response($msgType, $content);
    }

    //构建响应消息格式
    public function response($msgType, $content)
    {
        //回复用户消息(纯文本格式)
        $toUser = $this->openId;
        $fromUser = $this->myId;
        $time = time();
        $template = "<xml>
                    <ToUserName><![CDATA[%s]]></ToUserName>
                    <FromUserName><![CDATA[%s]]></FromUserName>
                    <CreateTime>%s</CreateTime>
                    <MsgType><![CDATA[%s]]></MsgType>
                    <Content><![CDATA[%s]]></Content>
                    </xml>";
        $info = sprintf($template, $toUser, $fromUser, $time, $msgType, $content);
        echo $info;
    }
}